repositories:
  - name: eks
    url: https://aws.github.io/eks-charts
releases:
  - name: aws-load-balancer-controller
    namespace: kube-system
    chart: eks/aws-load-balancer-controller
    version: 1.7.1
    values:
      - clusterName: my-cluster
        serviceAccount:
          create: false
          name: aws-load-balancer-controller