---
- name: Apply Kubernetes resources from a combined YAML
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3
    repo_url: https://github.com/mahinsat/bluegreenaws.git
    dest_dir: /tmp/bluegreenaws
    obj_def_path: /tmp/bluegreenaws/files/non-production/sub-system/artifacts
    manifest_file: my-app-deployment.yaml
    branch      : ESARME-11135
  tasks:
    - name: Ensure git is installed
      yum:
        name: git
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python2

    - name: Clone the private repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: "{{ branch }}"  # or any branch/tag you want to checkout
        force: yes

    - name: Ensure required Python packages are installed
      pip:
        name:
          - openshift
          - kubernetes
          - pyyaml
        executable: pip3

    - name: Apply all resources from single YAML file
      k8s:
        state: present
        src: "{{ obj_def_path }}/{{ manifest_file }}"
        apply: true