---
- name: Update EKS kubeconfig on remote host
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Run aws eks update-kubeconfig
      ansible.builtin.shell: >
        aws eks update-kubeconfig
        --region {{ region }}
        --name {{ cluster_name }}