---
- name: Install ALB controller to eks
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    repo_url: https://github.com/mahinsat/bluegreenaws.git
    dest_dir: /tmp/bluegreenaws
    obj_def_path: /tmp/bluegreenaws/files/non-production/sub-system/artifacts
    obj_def_list:
      - loadbalancer-service-account.yaml
    branch      : ESARME-11135
  tasks:
    - name: Ensure git is installed
      yum:
        name: git
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python2

    - name: Clone the private repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_dir }}"
        version: "{{ branch }}"  # or any branch/tag you want to checkout
        force: yes

    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
          - urllib3==1.26.18
        executable: pip3

    - name: Render service account template
      template:
        src: "{{ obj_def_path }}/loadbalancer-service-account.yaml.j2"
        dest: "{{ obj_def_path }}/loadbalancer-service-account.yaml"

    - name: Install all objects from def files
      k8s:
        src: "{{ obj_def_path }}/{{ item }}"
        state: present
        apply: true
      loop: "{{ obj_def_list }}"
    - name: Add AWS Helm Repo using shell
      ansible.builtin.shell: |
        helm repo add eks https://aws.github.io/eks-charts
        helm repo update
        helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
          --namespace {{ namespace }} \
          --set clusterName={{ cluster_name }} \
          --set serviceAccount.name={{ sa_name }} \
          --set serviceAccount.create=false \
          --set region={{ region }} \
          --set vpcId={{ vpc_id }} \             
          --set-string serviceAccount.annotations."eks\.amazonaws\.com/role-arn"={{ lb_controller_role_arn }}
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: /root/.kube/config
