- name: Convert dist to dist.tar.gz
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    prometheus_version: "{{ prometheus_version }}"

  tasks:
    - name: install pre-requisites
      pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
          - urllib3==1.26.18
        executable: pip3

    - name: Create a k8s namespace
      k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Add Prometheus to EKS
      ansible.builtin.shell: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        helm upgrade -i prometheus prometheus-community/prometheus \
        --namespace {{ namespace }} \
        --version {{ prometheus_version }} \
        --set server.persistentVolume.enabled=false \
        --set alertmanager.persistentVolume.enabled=false
      args:
        executable: /bin/bash
      environment:
        KUBECONFIG: /root/.kube/config
